1-Bibliotecas:

In [126]:
import scipy.io as io
import numpy as np
import h5py
import os
import matplotlib.pyplot as plt

2-variable to save the directory path to load your files and save your results

In [127]:
data_tst = r'C:\Users\Lenovo\.cache\DeepRadar_TST'

Now we load each file as a Numpy vector for it to be easy to use. The signal files were saved with an h5 format. We can load it with a float32 type to save space

In [128]:
path = r'C:\Users\Lenovo\.cache\kagglehub\datasets\khilian\deepradar\versions\1'

with h5py.File(os.path.join(path, 'X_train.mat'), 'r') as f:
    X_train = np.array(f['X_train'], dtype='float32').T

with h5py.File(os.path.join(path, 'X_val.mat'), 'r') as f:
    X_val = np.array(f['X_val'], dtype='float32').T

with h5py.File(os.path.join(path, 'X_test.mat'), 'r') as f:
    X_test = np.array(f['X_test'], dtype='float32').T

In [129]:
print("X train shape: ", X_train.shape)
print("X val shape: ", X_val.shape)
print("X test shape: ", X_test.shape)

X train shape:  (469200, 1024, 2)
X val shape:  (156400, 1024, 2)
X test shape:  (156400, 1024, 2)


Now we load the rest of the files regarding the class (Y) and labels (lbl)

In [130]:
Y_train = io.loadmat(os.path.join(path, 'Y_train.mat'))['Y_train']
Y_val   = io.loadmat(os.path.join(path, 'Y_val.mat'))['Y_val']
Y_test  = io.loadmat(os.path.join(path, 'Y_test.mat'))['Y_test']

lbl_train = io.loadmat(os.path.join(path, 'lbl_train.mat'))['lbl_train']
lbl_val   = io.loadmat(os.path.join(path, 'lbl_val.mat'))['lbl_val']
lbl_test  = io.loadmat(os.path.join(path, 'lbl_test.mat'))['lbl_test']

In [131]:
print("Y train shape: ", Y_train.shape)
print("Y val shape: ", Y_val.shape)
print("Y test shape: ", Y_test.shape)
print("Label train shape: ", lbl_train.shape)
print("Label val shape: ", lbl_val.shape)
print("Label test shape: ", lbl_test.shape)

Y train shape:  (469200, 23)
Y val shape:  (156400, 23)
Y test shape:  (156400, 23)
Label train shape:  (469200, 6)
Label val shape:  (156400, 6)
Label test shape:  (156400, 6)


In [132]:
import numpy as np

print(lbl_train.shape)
print(np.unique(lbl_train))

(469200, 6)
[ -12.  -10.   -8. ... 1015. 1020. 1024.]


In [133]:
print(Y_train.shape)
print(Y_train[:2])

(469200, 23)
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [134]:
y_train_idx = np.argmax(Y_train, axis=1)
y_val_idx   = np.argmax(Y_val, axis=1)
y_test_idx  = np.argmax(Y_test, axis=1)

In [135]:
print(np.unique(y_train_idx))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [136]:
for i in range(23):
    print(i, np.sum(y_train_idx == i))

0 20400
1 20400
2 20400
3 20400
4 20400
5 20400
6 20400
7 20400
8 20400
9 20400
10 20400
11 20400
12 20400
13 20400
14 20400
15 20400
16 20400
17 20400
18 20400
19 20400
20 20400
21 20400
22 20400


cada classe é independente e balanceada de um cenário gerado artificialmente.

In [137]:
for i in range(23):
    print(i, np.sum(y_test_idx == i))

0 6800
1 6800
2 6800
3 6800
4 6800
5 6800
6 6800
7 6800
8 6800
9 6800
10 6800
11 6800
12 6800
13 6800
14 6800
15 6800
16 6800
17 6800
18 6800
19 6800
20 6800
21 6800
22 6800


In [138]:
for i in range(23):
    print(i, np.sum(y_val_idx == i))

0 6800
1 6800
2 6800
3 6800
4 6800
5 6800
6 6800
7 6800
8 6800
9 6800
10 6800
11 6800
12 6800
13 6800
14 6800
15 6800
16 6800
17 6800
18 6800
19 6800
20 6800
21 6800
22 6800


We have generated a set of signals with 23 modulations commonly used in radar applications. Each dataset item consists on a 1024x2 vector that represents the In-phase and Quadrature (I + jQ) time samples of a modulated signal with a noise contribuition. For each of the modulations, we considered Signal-to-Noise Ratio (SNR) values within the range (-12,20)dB with a step of 2 dB.
The following modulations have been considered as Classes:
# 1- Linear Frequency Modulation (LFM)
2- Binary Frequency-Shift Keying 2FSK
3- Frequency-Shift Keying 4FSK
4- Frequency-Shift Keying 8FSK
# 5- Frequency Modulation with Costas code
6- Binary Phase-Shift Keying 2PSK
7- Phase-Shift Keying4PSK
8- Phase-Shift Keying 8PSK
# 9- Phase Modulation with Barker code
10- Phase modulation with Huffman code
# 11- Phase modulation with Frank code
# 12- Phase modulation with P1 code
# 13- Phase modulation with P2 code
# 14- Phase Modulation with P3 code
# 15- Phase modulation with P4 code
16- Phase modulation with Px code
17- Phase modulation with Zadoff-Chu code
18- Phase modulation with T1 code
19- Phase modulation with T2 code
20- Phase modulation with T3 code
21- Phase modulation with T4 code
# 22- Non-modulation (NM)
# 23- Complex White Gaussian Noise (Noise)

In [139]:
target_idx = [0, 4, 8, 10, 11, 12, 13, 14, 21, 22] # indices do filtro

In [178]:
def filter_split(X, y, lbl, target_idx): #função do filtro
    mask = np.isin(y, target_idx)
    return X[mask], y[mask], lbl[mask]

In [141]:
X_train_f, y_train_f, lbl_train_f = filter_split(X_train, y_train_idx, lbl_train, target_idx)
X_val_f, y_val_f, lbl_val_f = filter_split(X_val, y_val_idx, lbl_val, target_idx)
X_test_f, y_test_f, lbl_test_f = filter_split(X_test, y_test_idx, lbl_test, target_idx)

In [187]:
print(X_train_f.shape)
print(X_val_f.shape)
print(X_test_f.shape)
print(len(np.unique(y_train_f)))

(204000, 1024, 2)
(68000, 1024, 2)
(68000, 1024, 2)
10


In [188]:
print(sorted(np.unique(y_train_f)))

[np.int64(0), np.int64(4), np.int64(8), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(21), np.int64(22)]


In [189]:
print(X_train_f.shape)
print(X_val_f.shape)
print(X_test_f.shape)
print(len(np.unique(y_train_f)))

(204000, 1024, 2)
(68000, 1024, 2)
(68000, 1024, 2)
10


In [199]:
print("X_train:", X_train_f.shape)
print("y_train:", y_train_f.shape)
print("lbl_train:", lbl_train_f.shape)

X_train: (204000, 1024, 2)
y_train: (204000,)
lbl_train: (204000, 6)


In [200]:
X_train_mlp = X_train_f.reshape(X_train_f.shape[0], -1)
X_val_mlp   = X_val_f.reshape(X_val_f.shape[0], -1)
X_test_mlp  = X_test_f.reshape(X_test_f.shape[0], -1)

In [201]:
print(X_train_mlp.shape)
print(X_val_mlp.shape)
print(X_test_mlp.shape)

(204000, 2048)
(68000, 2048)
(68000, 2048)


In [202]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_mlp = scaler.fit_transform(X_train_mlp)
X_val_mlp   = scaler.transform(X_val_mlp)
X_test_mlp  = scaler.transform(X_test_mlp)

In [213]:
y_train_mlp = y_train_f
y_val_mlp = y_val_f

In [214]:
y_train_f.shape

(204000,)

In [215]:
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_mlp.shape[1],)),

    tf.keras.layers.Dense(1024, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(256, activation='relu'),

    tf.keras.layers.Dense(len(np.unique(y_train_f)), activation='softmax')
])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,760,970 (10.53 MB)

 Trainable params: 2,758,922 (10.52 MB)

 Non-trainable params: 2,048 (8.00 KB)

In [216]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)



In [217]:
model.fit(
    X_train_mlp, y_train_mlp,
    validation_data=(X_val_mlp, y_val_mlp),
    epochs=20,
    batch_size=256
)

Epoch 1/20


InvalidArgumentError: Graph execution error:

Detected at node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits defined at (most recent call last):
  File "C:\Users\Lenovo\anaconda3\Lib\runpy.py", line 198, in _run_module_as_main

  File "C:\Users\Lenovo\anaconda3\Lib\runpy.py", line 88, in _run_code

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 211, in start

  File "C:\Users\Lenovo\anaconda3\Lib\asyncio\base_events.py", line 683, in run_forever

  File "C:\Users\Lenovo\anaconda3\Lib\asyncio\base_events.py", line 2050, in _run_once

  File "C:\Users\Lenovo\anaconda3\Lib\asyncio\events.py", line 89, in _run

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 519, in dispatch_queue

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 508, in process_one

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 400, in dispatch_shell

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 368, in execute_request

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 455, in do_execute

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 602, in run_cell

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3116, in run_cell

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3171, in _run_cell

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3394, in run_cell_async

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3639, in run_ast_nodes

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3699, in run_code

  File "C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15612\971580554.py", line 1, in <module>

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 399, in fit

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 241, in function

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 154, in multi_step_on_iterator

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 125, in wrapper

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 134, in one_step_on_data

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 62, in train_step

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\trainers\trainer.py", line 405, in _compute_loss

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\trainers\trainer.py", line 373, in compute_loss

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\trainers\compile_utils.py", line 707, in __call__

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\trainers\compile_utils.py", line 732, in call

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\losses\loss.py", line 67, in __call__

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\losses\losses.py", line 33, in call

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\losses\losses.py", line 2355, in sparse_categorical_crossentropy

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\ops\nn.py", line 2189, in sparse_categorical_crossentropy

  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\nn.py", line 1252, in sparse_categorical_crossentropy

Received a label value of 22 which is outside the valid range of [0, 10).  Label values: 11 14 4 4 10 0 12 22 14 13 12 10 12 8 4 12 8 0 21 13 21 22 4 0 4 22 21 12 0 22 11 12 11 11 21 0 10 10 14 12 8 12 4 13 12 11 22 14 12 11 14 8 22 0 0 10 0 12 21 14 14 21 13 10 21 22 14 8 8 14 8 8 12 11 11 13 22 4 14 12 21 22 10 14 8 10 21 4 10 8 8 8 8 12 13 22 4 14 13 12 11 21 22 11 22 0 4 0 14 14 21 22 4 22 22 14 22 8 14 22 4 8 0 8 14 14 21 0 21 14 0 8 8 11 21 22 8 4 11 8 4 13 11 21 13 0 4 13 21 0 8 13 4 14 11 14 14 21 8 8 11 21 13 10 21 10 14 10 12 11 22 14 8 12 13 22 21 4 8 10 11 12 4 8 13 11 8 10 13 0 11 14 21 14 22 22 13 12 13 12 22 14 22 10 21 4 21 13 12 22 14 21 21 21 14 14 8 22 12 0 12 21 13 10 13 13 12 13 8 21 12 12 8 13 13 11 10 21 4 14 11 8 21 22 22 8 0 22 22 0 21 14 8 10 12 4
	 [[{{node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_multi_step_on_iterator_2527]

In [171]:
I = X_train_f[:, :, 0]
Q = X_train_f[:, :, 1]

amplitude = np.sqrt(I**2 + Q**2)
phase = np.arctan2(Q, I)

In [173]:
print(amplitude.shape)
print(phase.shape)

(204000, 1024)
(204000, 1024)


In [174]:
X_new = np.concatenate([amplitude, phase], axis=1)

In [175]:
X_new.shape

(204000, 2048)

In [176]:
import pandas as pd

df = pd.DataFrame(lbl_train_f, columns=[
    "class", "SNR", "length",
    "carrier_freq", "symbol_rate",
    "freq_excursion"
])

df["y"] = y_train_f

In [177]:
df[df["y"] == 0].head() # 5 primeiras linhas para a classe 0

,class,SNR,length,carrier_freq,symbol_rate,freq_excursion,y
0,1.0,-12.0,1024.0,0.004227,0.128290,0.0,0
1,1.0,-12.0,1024.0,0.200246,0.079875,0.0,0
2,1.0,-12.0,1024.0,0.126934,0.225750,0.0,0
3,1.0,-12.0,1024.0,0.064824,0.146626,0.0,0
4,1.0,-12.0,1024.0,0.062099,0.112184,0.0,0


In [102]:
map_10 = {
    0: 0,
    4: 1,
    8: 2,
    10: 3,
    11: 4,
    12: 5,
    13: 6,
    14: 7,
    21: 8,
    22: 9
}

In [103]:
y_train_f = np.array([map_10[i] for i in y_train_f])
y_val_f   = np.array([map_10[i] for i in y_val_f])
y_test_f  = np.array([map_10[i] for i in y_test_f])

In [104]:
print(sorted(np.unique(y_train_f)))

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]


In [105]:
print(len(np.unique(y_train_f)))

10


In [107]:
print("X_train:", X_train_f.shape)
print("y_train:", y_train_f.shape)
print("lbl_train:", lbl_train.shape)

X_train: (204000, 1024, 2)
y_train: (204000,)
lbl_train: (469200, 6)


EXTRA:Additionally, in order to use them with your model the data should be randomly shuffled. An example of this procedure:

In [ ]:
from sklearn.utils import shuffle

np.random.seed(1961)

X_train, Y_train, lbl_train = shuffle(
    X_train[:], Y_train[:], lbl_train[:],
    random_state=1961
)

X_val, Y_val, lbl_val = shuffle(
    X_val[:], Y_val[:], lbl_val[:],
    random_state=1961
)

X_test, Y_test, lbl_test = shuffle(
    X_test[:], Y_test[:], lbl_test[:],
    random_state=1961
)